### ISSUE TITLE
Is the project still maintained?

### ISSUE THREAD

**Issue by posixrails** [SwiftyJSON/SwiftyJSON#1090]
Hey, I made a pull request 1 month ago and nobody still merged/closed it. Is the project dead?

**Comment by Ariandr** [comment]
Hi, I'm also interested in this.

Hello @LukeTangPL @lingoer @wongzigii, do you have something to say about it?

**Comment by Ariandr** [comment]
This project has 20K+ stars and is used on more than 100K projects for sure, including several of mine. It would be a pity to have it dead :(

**Comment by ethanwa** [comment]
Yeah I hope it's not dead. We use it a lot.

**Comment by lingoer** [comment]
Hmmmmm, actually, it's dead for almost 2 years now. I kept suggesting people considering apple's Codable api to gain a much robust model layer in there app.
However, I'm considering restart the maintenance of this project recently. The reason is the raise of it's use cases in linux platform (mostly server side).

**Comment by Ariandr** [comment]
Hi @lingoer 
Great consideration!
It's a great idea to keep maintenance. Even on iOS in many cases SwiftyJSON can do some things way easier than Codable, especially when it comes to optionals and custom use cases.

**Comment by posixrails** [comment]
> Hmmmmm, actually, it's dead for almost 2 years now. I kept suggesting people considering apple's Codable api to gain a much robust model layer in there app.
> However, I'm considering restart the maintenance of this project recently. The reason is the raise of it's use cases in linux platform (mostly server side).

Thanks for your reply, I guess now I may close the issue since we received a message from you.

**Comment by tsfischer** [comment]
We have a major app where we used this library and (perhaps unfortunately) made heavy use of the JSON data type. While I realize Swift language has come a long way since SwiftyJSON was envisioned, it's often non-trivial for projects to simply switch over to use the native functionality. 

I hope this library can be maintained at least to the minimal point of keeping it working with language updates, and approving community PRs and such.

**Comment by Ariandr** [comment]
@tsfischer 
Yes, we have the same thing and thousands of other apps are relying on SwiftyJSON too.

I also hope it will be supported at least to keep up with language updates.
