### ISSUE TITLE
Privacy Manifest

### ISSUE THREAD

**Issue by wlxo0401** [SwiftyJSON/SwiftyJSON#1145]
Need Privacy Manifest

https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api

https://developer.apple.com/support/third-party-SDK-requirements/

**Comment by kalsariyarahul** [comment]
Need Privacy Manifest

https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api

https://developer.apple.com/support/third-party-SDK-requirements/

**Comment by mha1der** [comment]
It's time to switch to apple's JSONDecoder. I took this as an opportunity to remove SwiftyJSON from my projects. A lot of effort, but it's worth it.

**Comment by Nathan-Molby** [comment]
The best solution is to use Apple's Codable framework. However, if you don't have the capacity to migrate your entire data layer, I've created a fork that adds a privacy manifest to SwiftyJSON. The fork is [here](https://github.com/Nathan-Molby/SwiftyJSON/tree/master) and the PR is [here](https://github.com/SwiftyJSON/SwiftyJSON/pull/1150). 

@wongzigii can you merge the above PR and create a new release so that people don't have to use the fork?

**Comment by wlxo0401** [comment]
> The best solution is to use Apple's Codable framework. However, if you don't have the capacity to migrate your entire data layer, I've created a fork that adds a privacy manifest to SwiftyJSON. The fork is [here](https://github.com/Nathan-Molby/SwiftyJSON/tree/master) and the PR is [here](https://github.com/SwiftyJSON/SwiftyJSON/pull/1150). 
> 
> 
> 
> @wongzigii can you merge the above PR and create a new release so that people don't have to use the fork?

Thank you for your response.🤩🤩

**Comment by wongzigii** [comment]
Closing with https://github.com/SwiftyJSON/SwiftyJSON/pull/1150

**Comment by allancanare** [comment]
It seems 5.0.2 that contains this fix is not yet released in cocoapods. Any update on when can we have it released in cocoapods as well?
