### ISSUE TITLE
Update to Swift 1.2

### ISSUE THREAD

**Issue by Harper04** [SwiftyJSON/SwiftyJSON#148]
Xcode 6.3 and Swift 1.2 beta is out :)

Please make it compatible to it. I think most of the compile errors are due to this:

* as! for failable casts — Casts that can fail at runtime are now expressed with the new as! operator to make their potential for runtime failure clear to readers and maintainers of your code.

* The implicit conversions from bridged Objective-C classes (NSString/NSArray/NSDictionary) to their
corresponding Swift value types (String/Array/Dictionary) have been removed, making the Swift type
system simpler and more predictable. (18311362)

**Comment by mkoppanen** [comment]
We are experiencing the same issue. The fixes are fairly simple but it looks like it would break backwards compatibility with Swift <1.2

**Comment by leegoodrich** [comment]
Yeah, the Swift 1.2 converter provided by Xcode 6.3 got it about 95% of the way to building correctly for me. A few other issues I ran into were:

- The compiler now complains about an integer overflow in [this line within the base tests](https://github.com/SwiftyJSON/SwiftyJSON/blob/master/Tests/BaseTests.swift#L119). Not knowing the context for that assert, I just commented it out. The remaining test cases all passed.

- I'm ingesting SwiftyJSON via Carthage, and using the SwiftyJSON.framework compiled with Xcode 6.1 with Xcode 6.3 did not work for me: the linker complained about the framework being built by an older compiler. So I needed to compile the framework with 6.3, and if you are doing the same you need to make sure to change your Xcode commandline tools to point to Xcode 6.3 within Xcode's preferences. Also, after fixing up the SwiftyJSON source code, make sure to use "carthage build" instead of "update", as that will wipe out all your local changes before building, reverting all the instances of "as!" back to "as" and generating a ton of errors.

As for the backwards compatibility issue, can't you make the changes and tag it as a major version update, i.e. 3.0.0, and advise all non-beta users to stay on 2.x.x?

**Comment by tangplin** [comment]
Please check out branch `xcode6.3`. After the xcode 6.3 beta test , there will be a new tag like 3.0.

**Comment by pip8786** [comment]
Is there a way to get these fixes using Pods or do we have to wait for it to be merged in?

**Comment by vertgo** [comment]
I got mine compiling and working for the amount of code I use, anyways

https://gist.github.com/vertgo/fa1f811a255db6bcb304

Does this help anyone?

**Comment by amcuserguy** [comment]
Got an error after updating latest xcode.

![screen shot 2015-04-13 at 12 05 01 pm](https://cloud.githubusercontent.com/assets/338406/7109698/82f742a0-e1d5-11e4-8eb8-c60082edc415.png)

**Comment by dfreniche** [comment]
@pip8786 you can check out the branch that supports Swift 1.2 just adding to your Podfile:

        pod 'SwiftyJSON', :git => 'https://github.com/SwiftyJSON/SwiftyJSON.git', :branch => 'xcode6.3'

**Comment by germanger** [comment]
I only see a "master" branch... was that "xcode6.3" branch merged?

**Comment by dfreniche** [comment]
Yes, last version works with Swift 1.2 just using the pod name
