### ISSUE TITLE
Why does SwiftyJSON overwrite comparison operators for NSNumber?

### ISSUE THREAD

**Issue by doschi** [SwiftyJSON/SwiftyJSON#302]
Hi,
First:
Thanks for writing/maintaining SwiftyJSON!
I really like it.

My Question/Problem is:
SwiftyJSON overwrites the default behaviour of the comparison operators for NSNumber. (==,!=,<,>...)
I.e. comparing 1 == true now gives false instead of true
What is the reason for that?

I just had a bug that was caused only by importing SwiftyJSON in some file and therefore pretty magical to debug...
Is it absolutely necessary to change such basic functionality?

**Comment by Nelyus** [comment]
+1

**Comment by Danappelxx** [comment]
I believe it's due to how booleans are handled internally. When determining type, it's difficult to know whether it's a boolean (0,1) or a number, so SwiftyJSON does some clever things with NSNumber to figure out which one it is. I assume overloading the equality operator is (unfortunately) part of this.

**Comment by gereons** [comment]
+1, was just bitten by the same issue.

**Comment by zhigang1992** [comment]
Hi guys, just did a fix and make the operator overload internal to SwiftyJSON. It shouldn't affecting outside the framework anymore.
