### ISSUE TITLE
Manipulating a JSON! (implicitly unwrapped) variable fails to modify the underlying json

### ISSUE THREAD

**Issue by yikuo123** [SwiftyJSON/SwiftyJSON#412]
//setter does not work,data1 has no element
var data1:JSON!
data1 = JSON([:])
data1["sn"].string = "1111"

//this is ok
var data2:JSON = JSON([:])
data2 = JSON([:])
data2["sn"].string = "1111"

//also ok
var data3:JSON = JSON.null
data3 = JSON([:])
data3["sn"].string = "1111"

**Comment by djdance** [comment]
var data = JSON.parse("") not work too :-( i.e. - date has no element for "sn"

**Comment by madsonic** [comment]
bump

**Comment by ldiqual** [comment]
@yikuo123 Sorry for the delay on this. I was able to reproduce by using your code above, I'll look more into this asap.
@djdance `JSON.parse("")` not working is intended, because the provided string is not a valid JSON string. I'm proposing a new initializer here https://github.com/SwiftyJSON/SwiftyJSON/issues/459#issuecomment-262155181, please add a 👍 if you think it'd be valuable (especially the `throws` part). Thanks!

**Comment by ldiqual** [comment]
Closing as duplicate of https://github.com/SwiftyJSON/SwiftyJSON/issues/215
