### ISSUE TITLE
why JSON('string') not work? and other issues

### ISSUE THREAD

**Issue by djdance** [SwiftyJSON/SwiftyJSON#435]
Let's try

```
                    let s="{\"res\": \"Warning\"}"
                    //let s2="{'res': 'Warning'}"
                    let json = JSON(s)
                    let json1 = JSON(data: s.dataUsingEncoding(NSUTF8StringEncoding)!)
                    let json2 = JSON.parse(s)
                    print("json=\(json["res"].string), json1=\(json1["res"].string), json2=\(json2["res"].string)")
```
output: *json=nil, json1=Optional("Warning"), json2=Optional("Warning")*

Questions:

1. Why first json is nil? What kind of string has to be s?
2. Why no notes about JSON.parse() in start page/manual/docs? I'd found it in issues after 2 hours of search. Please add to manual
3. Why commented **let s2=...** is not possible in any case? Can it be made possible?

thanks

**Comment by voidref** [comment]
This framework has been designed to use with the way Cocoa works with http requests, which is with a block of data instead of strings. You could always make an extension to the json object with a convenience init that takes a string and converts it to the NSData format the framework is expecting.

I recommend you put each of your issues in a separate ticket, just like you would with regular bug reports so they can be tracked individually.

(Not associated with this project, just trying to help)

**Comment by djdance** [comment]
okay, just leave *strings questions* here for someone who will be confused about it too.
yes, stranger, do no do so as described above.

parse added to ticket
https://github.com/SwiftyJSON/SwiftyJSON/issues/459
