### ISSUE TITLE
Feature Request: Access JSON's Parent

### ISSUE THREAD

**Issue by AnthonyMDev** [SwiftyJSON/SwiftyJSON#452]
I'd like to add an optional `parent` property that returns the `JSON` dictionary/array that a `JSON` object is contained in.

I'd also like an optional `parentKey` property (not sure on the name for this one) that would return the key on the `parent` that is used to access the `JSON` object.

I'd be willing to assist in implementing this, but I wanted to check for interest first.

**Comment by ldiqual** [comment]
@AnthonyMDev Given that nobody has responded to this issue, I'm assuming that not a lot of people think that it could be part of their workflow. I personally fail to see the usecase here, and even if I had to refer to the parent, I would implicitly have that reference in my code because I would have provided the json path. I'm gonna go ahead and close this, let me know if you'd like me to reopen. Thanks!
