### ISSUE TITLE
CocoaPods repo doesn't have latest release of SwiftyJSON

### ISSUE THREAD

**Issue by otaran** [SwiftyJSON/SwiftyJSON#581]
- Latest release is `2.3.3`, but `SwiftyJSON.podspec` sets version to `2.3.2`.
- CocoaPods repo doesn't have latest release: https://cocoapods.org/pods/SwiftyJSON (note `2.3.2` next to `SwiftyJSON` header).

Since `2.3.3` version has already been tagged, I think this can only be fixed in version `2.3.4`.

**Comment by CharlesGrimont** [comment]
* I Have to release my Pod which depends on SwiftyJSON.
* I can't submit it to CocoaPod due to :

```
warning: '++' is deprecated: it will be removed in Swift 3
```

* Latest release is 2.3.3 which still doesn't fix this, the master already has the fix.

Please update your Pod ASAP

Many thanks 😄

**Comment by amarcadet** [comment]
@CharlesGrimont You could use `--allow-warnings` as a temporary fix to submit your pod, I have only used it on private specs but it should work.

But +1 for the release!

**Comment by amarcadet** [comment]
@otaran it could be fixed without tagging 3.2.4 as versions are related to tags.

However you can fix your problem using the `:commit` or `:tag` syntax in your Podfile. Not a long term solution but a decent one in the meantime.
See https://guides.cocoapods.org/syntax/podfile.html#pod for more information.

**Comment by otaran** [comment]
Thanks for a workaround, @amarcadet!

I am not sure I understand what you mean by "versions are related to tags". `SwiftyJSON.podspec` uses git tag to get pod source code. If maintainer will update pod version to `2.3.3`, it will point to `2.3.3` tag which doesn't include changes made to `SwiftyJSON.podspec`. If I understand this issue correctly, maintained will need to first update podspec, then tag commit which has changes made to podspec.

**Comment by amarcadet** [comment]
You're welcome :)

Actually, it doesn't matter if the `.podspec` currently commited in the tag `2.3.3` has version `2.3.2` because cocoapods use [the spec published in the specs repo](https://github.com/CocoaPods/Specs/blob/master/Specs/SwiftyJSON/2.3.2/SwiftyJSON.podspec.json#L22) and only the version in that file really matters when running `pod [install|update]`.

During the process of pushing a new version, cocoapods use the tag currently defined in the local `.podspec` to checkout the pod directly from the git repo and check if everything compile without issues. That's why you need to tag a version before pushing it to cocoapods.

So in theory, publishing the `2.3.3` afterwards is possible! Hope it's clear!

**Comment by otaran** [comment]
Ah, I see, now it makes sense, thank you!

**Comment by ldiqual** [comment]
@otaran I believe your issue was addressed so I'll go ahead and close this. Let me know if we need to reopen!
