### ISSUE TITLE
extension type of JSON cannot inherit from class collection

### ISSUE THREAD

**Issue by JsonWong87** [SwiftyJSON/SwiftyJSON#689]

**Comment by wongzigii** [comment]
If I understand you correctly, you are trying to inherit a JSON from a class. I don't think structs in Swift have inheritance since now. :(

**Comment by ldiqual** [comment]
@JsonWong87 I believe your issue was addressed by @wongzigii so I'm gonna go ahead and close this. If you have a use case where you think `JSON` should be subclassed, please feel free to file an enhancement issue so we can evaluate whether to add it to the library directly. Another solution for you would be to use extensions. Let me know if you need to reopen!

**Comment by JsonWong87** [comment]
got it , thank you


发自网易邮箱大师
On 11/22/2016 12:27, Loïs Di Qual wrote:

@JsonWong87 I believe your issue was addressed by @wongzigii so I'm gonna go ahead and close this. If you have a use case where you think JSON should be subclassed, please feel free to file an enhancement issue so we can evaluate whether to add it to the library directly. Another solution for you would be to use extensions. Let me know if you need to reopen!
