### ISSUE TITLE
Nested JSON - .rawString() works, .stringValue is nil

### ISSUE THREAD

**Issue by mattwitkowicz** [SwiftyJSON/SwiftyJSON#720]
I've got nested JSON such as this simple example:
```
{
  "questions" : {
    "20161111" : {
      "id" : "1",
      "name" : "Q1"
    }
  }
}
```

Created using:
```
let json = JSON(["questions": ["20161111": ["id": "1", "name": "Q1"]]])
```

However trying to get the .stringValue of json["questions"] returns nil:
```
print(json["questions"].stringValue)
nil
```

But getting the rawString() is fine
```
{
  "20161111" : {
    "id" : "1",
    "name" : "Q1"
  }
}
```

**Comment by TheNamesJames** [comment]
Firstly, a minor syntactic clarification: `.stringValue` never returns `nil`. Another property, `.string` _will_ return `nil` if the value of that `JSON` instance is not a `String`.
`.stringValue` on the other hand, will return an empty string (`""`) in these cases.

**n.b.** From here on, I will assume you meant `.string` instead of `.stringValue`.

With that (brief) definition of `.string`, we can now start to see why calling `.string` on `json["questions"]` returns `nil`. While the json at `json["questions"]` can be represented as a string, it is not _actually_ a `String`.


```
{
  "20161111" : {
    "id" : "1",
    "name" : "Q1"
  }
}
```
The above is a `String` representation of a Javascript object (specifically a `Dictionary`). It consists of a single `String` key (`"20161111"`) with another object as its value (`{ "id" : "1", "name" : "Q1" }`). That object is also a `Dictionary`, consisting of two `String` keys (`"id"` and `"name"`), each with `String` values (`"1"` and `"Q1"` respectively).

As the value at `json["questions"]` is a `Dictionary`, we can call `.dictionary` to retrieve the actual object.

_side note:_ This is not actually an issue. If you have any questions with how to use libraries like this one, try asking/searching [StackOverflow](http://stackoverflow.com/)

**Comment by mattwitkowicz** [comment]
Yes I did actually mean .string was returning nil. 

Thank you for the explanation. Since I actually want the full JSON string .rawString() is what I need.
