### ISSUE TITLE
Error in swift  3.0.1

### ISSUE THREAD

**Issue by reshadf** [SwiftyJSON/SwiftyJSON#769]
Hi I am getting the following error in xcode after updating my dependencies for swift 3+ I use the latest Carthage version and all the other dependencies work just right. ( Kingfisher, Alamofire etc )
>Module compiled with Swift 3.0 cannot be imported in Swift 3.0.1: /Users/username/xcode/project/Carthage/Build/iOS/SwiftyJSON.framework/Modules/SwiftyJSON.swiftmodule/x86_64.swiftmodule

**Comment by VojtaStavik** [comment]
I had the same issue. The provided framework binary is built for 3.0, not 3.0.1. I solved it by running:
```
carthage update --no-use-binaries SwiftyJSON
```

**Comment by reshadf** [comment]
That seems to solve the problem! thanks

**Comment by Gujci** [comment]
The problem is, that Xcode 8, 8.1, 8.2 uses different compiler, and the compiled binary is not compatible (at least according to Xcode). If you use `carthage update` without `--no-use-binaries`, Carhage downloads the related GitHub release binary, which was compiled (accotding to the .travis.yml) file with Xcode 8, therefore it is swift 3.0.

So, if you don't want to compile the code locally, you have to:

-  fork the repo
-  change the .travis.yml file
 `osx_image: xcode8.1` for 3.0.1 or `osx_image: xcode8.2` for 3.0.2
 `repo: SwiftyJSON/SwiftyJSON` to the forked repo
-  tag and push
-  wait for travis to complete the release (change the simulators if needed)
-  change the line in the Cartfile to >yourname</SwiftyJSON

The main SwiftyJSON repo can make this change as well, but since a lot of developers still using Xcode 8, I don't  think this will happen soon.

**Comment by wongzigii** [comment]
Hello there! I just uploaded a latest archive file compiled with Swift 3.0.2. This issue will be closed now. Thanks for filling an issue. Cheers! 👏
