### ISSUE TITLE
Can I download the 3.0.2 compatible binary with Carthage

### ISSUE THREAD

**Issue by Gujci** [SwiftyJSON/SwiftyJSON#778]
The 3.1.4 release contains the a binary compatible with swift 3.0. Is there any way to download the binary?
I know that there is a workaround, but the question is not about that.

**Comment by tasanobu** [comment]
@Gujci You can try the following command to build the source files on your local machine.
`carthage update --no-use-binaries SwiftyJSON`

**Comment by Gujci** [comment]
@tasanobu please read the issue, "I know that there is a workaround" means that I know that there is a workaround. 
The issue is not about that, it's about downloading the correct binary, not compiling it locally.
Also `github "SwiftyJSON/SwiftyJSON" "master"` is a workaround, which "forces" carthage to compile it locally, but that is not the answer to this question.

**Comment by solidcell** [comment]
@Gujci I also ran into this, so I forked the repo and uploaded a pre-built framework built with Swift `3.0.2`.

You can point your `Cartfile` here in the meantime until they (hopefully) build the next release with the latest Swift: https://github.com/solidcell/SwiftyJSON/releases

I think this is a better solution than having to run:
```
carthage bootstrap
carthage update --no-use-binaries SwiftyJSON
```
.. just because of `SwiftyJSON`.

**Comment by wongzigii** [comment]
Sorry for the late response. I just uploaded a latest binary which compiled with Swift 3.0.2, tagging with `3.1.4`. Cheers!
