### ISSUE TITLE
Invalid tag for 3.1.1 on CocoaPods/Spec repository

### ISSUE THREAD

**Issue by gr-orc** [SwiftyJSON/SwiftyJSON#839]
https://github.com/CocoaPods/Specs/blob/d0ec5a65e80656c8d78e12ff19f251df879e0bc2/Specs/b/e/4/SwiftyJSON/3.1.1/SwiftyJSON.podspec.json#L22

### What did you do?

try to install SwiftyJson 3.1.1 by `pod install`

### What did you expect to happen?

Install SwiftyJson 3.1.1 correctly.

### What actually happened instead?

```sh
[!] Error installing SwiftyJSON
[!] /usr/bin/git clone https://github.com/SwiftyJSON/SwiftyJSON.git /var/folders/lz/krk8j37d4fq4dbznskttfc4r0000gp/T/d20170421-9483-1dkvcle --template= --single-branch --depth 1 --branch v3.1.1
```

**Comment by GurdevSingh94** [comment]
Getting the same thing

**Comment by wongzigii** [comment]
Hi all, sorry for late response. 😢 

## **TL,DR:**

Replace 

    pod 'SwiftyJSON', '~> 3.1.1'

with

    pod 'SwiftyJSON-3.1.1'


## What happens:

It seems like the [CocoaPods/Spec](https://github.com/CocoaPods/Specs/blob/d0ec5a65e80656c8d78e12ff19f251df879e0bc2/Specs/b/e/4/SwiftyJSON/3.1.1/SwiftyJSON.podspec.json#L22) is pointing to a wrong tag with a  'v' prefix as this issue stated.

I just try running `pod trunk push` to push a new `3.1.1` tag so that we can replace the old podspec. Unfortunately, it seems that this is not a recommend way due to [this](https://github.com/CocoaPods/Specs/pull/12199) 

>  If you want to modify an existing CocoaPod you should be shipping a new patch version.

> Can I submit a pull request if..
> Q: I want to update my Pod to a new version?
> A: No, this is no longer the appropriate way to update your Pod. Pod updates must be uploaded using pod trunk push [NAME.podspec].

and [this](http://stackoverflow.com/questions/25604601/how-to-do-pod-trunk-push-to-replace-an-existing-version-of-podspec).

> You cannot overwrite a spec using trunk. You should just push a new version with your changes. 

FWIW, So the workaround: I just pushed an new pod called **`SwiftyJSON-3.1.1`**, which should contain the old specific version:

    pod 'SwiftyJSON-3.1.1'

Let me know if there is still an issue.

Zigii Wong

**Comment by gr-orc** [comment]
@wongzigii
thank you for detailed information!
`3.1.1` is properly installed by the way you suggested.
