### ISSUE TITLE
Swift 4

### ISSUE THREAD

**Issue by Comanga** [SwiftyJSON/SwiftyJSON#871]
Just asking when do you think SwiftyJSON will be compatible with Swift 4?

Thank's for your amazing job.

**Comment by mludowise** [comment]
SwiftyJSON is compatible with Swift 4 syntax and libraries, however because the project has "Swift 3.0" set in its build settings so you can't currently add it in as-is.

I was able to include SwiftyJSON in my Swift 4 project by changing the build settings to use "Swift 4.0" and everything worked fine. You can access these updates from a branch on my fork:
https://github.com/mludowise/SwiftyJSON/tree/swift-4

Some updates to supporting files would be needed to get it working with Carthage, Cocoapods, and Swift Package Manager, but I don't have any familiarity with those and how to update them.

**Comment by codeslubber** [comment]
Damn can't someone add this to the product? as a tag? or a branch? kind of like leaving a manhole with no cones around it. Xcode 9 has been available for months.. (all the good things about the SJ syntax, readability, ease of use, just bled back out of me fiddling with build nonsense.. trying to get ready for a release that is now < 30  days away, not exactly a crazy expectation....).

**Comment by mludowise** [comment]
@codeslubber You're welcome to use the [branch in my forked repo](https://github.com/mludowise/SwiftyJSON/tree/swift-4), but I'm hesitant to create a Pull Request for it because I don't know how to configure it for CocoaPods, Carthage, or Swift Package Manager. If you're familiar with configuring any of these, then I encourage you to open a PR with those changes.

**Comment by wongzigii** [comment]
Hey @codeslubber @mludowise @Comanga Sorry for the late response!
I am downloading Xcode 9(4.7 GB) at this time so I am going to cut a new version asap for the coming several days.

**Comment by Comanga** [comment]
@wongzigii You rock

**Comment by racer1988** [comment]
I actually have the wrong problem. In Xcode 8 (using Xcode8 toolchain) I now have the following:

Module compiled with Swift 4.0 cannot be imported in Swift 3.1: .../Carthage/Build/iOS/SwiftyJSON.framework/Modules/SwiftyJSON.swiftmodule/i386.swiftmodule

**Comment by wongzigii** [comment]
@racer1988 I am drafting a prerelease note and suppose to make it tomorrow. Sorry for the inconvience. see #880

**Comment by wongzigii** [comment]
@all SwiftyJSON 4.0.0-alpha.1 is out! Cheers!

**Comment by esusslin** [comment]
Hey guys - where can i download SwiftyJSON.framework for Swift 4?  Really now the latest .framework file on the release page is 3.1.6...   This is most confusing
